CREATE DATABASE [VENDAS SUCOS]

CREATE TABLE PRODUTOS
(CODIGO VARCHAR(10) NOT NULL,
 DESCRITOR VARCHAR(100) NULL,
 SABOR VARCHAR(50) NULL,
 TAMANHO VARCHAR(50) NULL,
 EMBALAGEM VARCHAR(50) NULL,
 [PRECO LISTA] FLOAT NULL,
 CONSTRAINT [PK_PRODUTOS] PRIMARY KEY CLUSTERED (CODIGO))

CREATE TABLE VENDEDORES
( MATRICULA VARCHAR(5) NOT NULL,
  NOME VARCHAR(100) NULL,
  BAIRRO VARCHAR(50) NULL,
  COMISSAO FLOAT NULL,
  [DATA ADMISSAO] DATE NULL,
  FERIAS BIT NULL,
  CONSTRAINT [PK_VENDEDORES] PRIMARY KEY CLUSTERED (MATRICULA))


CREATE TABLE CLIENTES
( CPF VARCHAR(11) NOT NULL,
  NOME VARCHAR(100) NULL,
  ENDERECO VARCHAR(150) NULL,
  BAIRRO VARCHAR(50) NULL,
  CIDADE VARCHAR(50) NULL,
  ESTADO VARCHAR(50) NULL,
  CEP VARCHAR(8) NULL,
  [DATA NASCIMENTO] DATE NULL,
  IDADE SMALLINT NULL,
  SEXO VARCHAR(1) NULL,
  [LIMITE CREDITO] FLOAT NULL,
  [VOLUME COMPRA] FLOAT NULL,
  [PRIMEIRA COMPRA] BIT NULL,
  CONSTRAINT [PK_CLIENTES] PRIMARY KEY CLUSTERED (CPF))

CREATE TABLE NOTAS
( NUMERO VARCHAR(5) NOT NULL,
  DATA DATE NULL,
  CPF VARCHAR(11) NOT NULL,
  MATRICULA VARCHAR(5) NOT NULL,
  IMPOSTO FLOAT,
  CONSTRAINT [PK_NOTAS] PRIMARY KEY CLUSTERED (NUMERO))


CREATE TABLE [ITENS VENDIDOS]
( NUMERO VARCHAR(5) NOT NULL,
  [CODIGO DO PRODUTO] VARCHAR(10) NULL,
  QUANTIDADE INT NULL,
  PRECO FLOAT NULL,
  CONSTRAINT PK_ITEM PRIMARY KEY CLUSTERED (NUMERO)) 

-- Comando para criar a foreign key
-- ALTER TABLE <TABLE'S NAME> WITH CHECK ADD CONSTRAINT <FOREIGN KEY NAME>
-- FOREIGN KEY(COLUMN NAME WHERE FK IS BEING CREATED) REFERENCES [TABLE NAME]
-- (COLUMN NAME FROM  WHERE THE FK IS BEING ASSOCIATED WITH)

ALTER TABLE NOTAS WITH CHECK ADD CONSTRAINT FK_NOTAS_CLIENTES
 FOREIGN KEY (CPF) REFERENCES CLIENTES(CPF)