-- Pegando dados de outro banco e inserindo no novo

-- Peguei todos os dados da tabela de produtos
SELECT 
	*
FROM
	SUCOS_VENDAS.DBO.[TABELA DE PRODUTOS]

-- Em seguida vou inserir esses dados na tabela de Produtos na base de dados Vendas Sucos
-- IMPORTANTE: PARA QUE TUDO DE CERTO O MELHOR SERIA COLOCAR ALIAS COM O MESMO NOME DA TABELA DESTINO
-- SE HOUVER CONFLITO DE PK OU FK, O BLOCO INTEIRO SERA REJEITADO
INSERT INTO PRODUTOS
( CODIGO,
  DESCRITOR,
  SABOR,
  TAMANHO,
  EMBALAGEM,
  [PRECO LISTA])
SELECT
	[CODIGO DO PRODUTO] AS CODIGO,
	[NOME DO PRODUTO] AS DESCRITOR,
	SABOR,
	TAMANHO,
	EMBALAGEM,
	[PREÇO DE LISTA] AS [PRECO LISTA]
FROM
	SUCOS_VENDAS.DBO.[TABELA DE PRODUTOS]
WHERE 
	[CODIGO DO PRODUTO] <> '1040107'

-- Inclua todos os clientes na tabela CLIENTES baseados nos registros da tabela TABELA DE CLIENTES, da base SUCOS_VENDAS.
SELECT * FROM CLIENTES
SELECT * FROM SUCOS_VENDAS.DBO.[TABELA DE CLIENTES]

INSERT INTO CLIENTES
( CPF,
  NOME,
  ENDERECO,
  BAIRRO,
  CIDADE,
  ESTADO,
  CEP,
  [DATA NASCIMENTO],
  IDADE,
  SEXO,
  [LIMITE CREDITO],
  [VOLUME COMPRA],
  [PRIMEIRA COMPRA])
SELECT
	CPF,
	NOME,
	[ENDERECO 1] AS ENDERECO,
	BAIRRO,
	CIDADE,
	ESTADO,
	CEP,
	[DATA DE NASCIMENTO] AS [DATA NASCIMENTO],
	IDADE,
	SEXO,
	[LIMITE DE CREDITO] AS [LIMITE CREDITO],
	[VOLUME DE COMPRA] AS [VOLUME COMPRA],
	[PRIMEIRA COMPRA]
FROM
	SUCOS_VENDAS.DBO.[TABELA DE CLIENTES]
WHERE
	CPF NOT IN ('1471156710', '19290992743','2600586709')