-- Usando check

CREATE TABLE TAB_CHECK
( ID INT NOT NULL,
 NOME VARCHAR(20) NULL,
 IDADE INT NULL,
 CIDADE VARCHAR(20) NULL,
 CONSTRAINT CHK_PESSOA CHECK(IDADE >= 18))

INSERT INTO TAB_CHECK
	(ID, NOME, IDADE, CIDADE)
VALUES
	(1, 'Joao', 19, 'Rio de Janeiro')

INSERT INTO TAB_CHECK
	(ID, NOME, IDADE, CIDADE)
VALUES
	(2, 'Pedro', 20, 'Sao Paulo')

CREATE TABLE TAB_CHECK2
( ID INT NOT NULL,
 NOME VARCHAR(20) NULL,
 IDADE INT NULL,
 CIDADE VARCHAR(20) NULL,
 CONSTRAINT CHK_PESSOA2 CHECK(IDADE >= 18 AND CIDADE = 'RIO DE JANEIRO'))

INSERT INTO TAB_CHECK2
	(ID, NOME, IDADE, CIDADE)
VALUES
	(1, 'Joao', 19, 'Rio de Janeiro')

INSERT INTO TAB_CHECK2
	(ID, NOME, IDADE, CIDADE)
VALUES
	(2, 'Pedro', 20, 'Rio de Janeiro')

-- o CHECK tambem e aplicado para os comandos de update
UPDATE 
	TAB_CHECK2
SET
	CIDADE = 'SAO PAULO'
WHERE
	ID = 2