-- Usando MERGE para alterar dados

-- Pegando todas as informacoes das tabelas
SELECT
	*
FROM 
	SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS]
WHERE
	[CODIGO DO PRODUTO] = '1002334'

SELECT
	*
FROM
	PRODUTOS
WHERE
	CODIGO = '1002334'

-- Fazendo INNER JOIN para visualizar o preco do produto em abass tabelas
SELECT
	FONTE.[CODIGO DO PRODUTO],
	FONTE.[PREÇO DE LISTA],
	DESTINO.CODIGO,
	DESTINO.[PRECO LISTA]
FROM
	SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS] FONTE
	INNER JOIN
	PRODUTOS DESTINO
	ON FONTE.[CODIGO DO PRODUTO] COLLATE Latin1_General_CS_AS = DESTINO.CODIGO COLLATE Latin1_General_CS_AS
WHERE
	CODIGO = '1002334'

-- Vamos atualizar o preco na tabela fonte para logo podermos fazer o merge
UPDATE
	SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS]
SET 
	[PREÇO DE LISTA] = 8
WHERE
	[CODIGO DO PRODUTO] = '1002334'

-- Visualizando a tabela depois de alterar o valor
SELECT
	FONTE.[CODIGO DO PRODUTO] ,
	FONTE.[PREÇO DE LISTA] AS [PRECO FONTE],
	DESTINO.CODIGO,
	DESTINO.[PRECO LISTA] AS [PRECO DESTINO]
FROM
	SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS] FONTE
	INNER JOIN
	PRODUTOS DESTINO
	ON FONTE.[CODIGO DO PRODUTO] COLLATE Latin1_General_CS_AS = DESTINO.CODIGO COLLATE Latin1_General_CS_AS
WHERE
	CODIGO = '1002334'


-- Vamos atualizar o valor utilizando MERGE ao inves de UPDATE
MERGE INTO
	[PRODUTOS] DESTINO
USING
	SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS] FONTE
ON 
	FONTE.[CODIGO DO PRODUTO] COLLATE Latin1_General_CS_AS = DESTINO.[CODIGO] COLLATE Latin1_General_CS_AS
	AND CODIGO = '1002334'
WHEN MATCHED THEN
	UPDATE SET DESTINO.[PRECO LISTA] = FONTE.[PREÇO DE LISTA];

-- Visualizando nvoamente o resultado
SELECT
	FONTE.[CODIGO DO PRODUTO] ,
	FONTE.[PREÇO DE LISTA] AS [PRECO FONTE],
	DESTINO.CODIGO,
	DESTINO.[PRECO LISTA] AS [PRECO DESTINO]
FROM
	SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS] FONTE
	INNER JOIN
	PRODUTOS DESTINO
	ON FONTE.[CODIGO DO PRODUTO] COLLATE Latin1_General_CS_AS = DESTINO.CODIGO COLLATE Latin1_General_CS_AS
WHERE
	CODIGO = '1002334'