-- Atualizando dados de uma tabela com dados de outra tabela já existente

SELECT 
	*
FROM
	SUCOS_VENDAS.DBO.[TABELA DE PRODUTOS]
WHERE 
	[CODIGO DO PRODUTO] = '1000889'

SELECT 
	*
FROM
	PRODUTOS
WHERE 
	CODIGO = '1000889'

-- Atualizando o valor na tabela antiga
UPDATE
	SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS]
SET
	[PREÇO DE LISTA] = 7
WHERE
	[CODIGO DO PRODUTO] = '1000889'


-- Agora vamos atualizar a nova tabela fazendo um link entre as duas tabelas
SELECT
	FONTE.[CODIGO DO PRODUTO],
	FONTE.[PREÇO DE LISTA],
	DESTINO.CODIGO,
	DESTINO.[PRECO LISTA]
FROM
	SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS] FONTE
	INNER JOIN
	PRODUTOS DESTINO
	ON FONTE.[CODIGO DO PRODUTO] COLLATE Latin1_General_CS_AS = DESTINO.CODIGO COLLATE Latin1_General_CS_AS
WHERE
	DESTINO.CODIGO = '1000889'


UPDATE
	DESTINO
SET
	DESTINO.[PRECO LISTA] = FONTE.[PREÇO DE LISTA]
FROM
	SUCOS_VENDAS.dbo.[TABELA DE PRODUTOS] FONTE
	INNER JOIN
	PRODUTOS DESTINO
	ON FONTE.[CODIGO DO PRODUTO] COLLATE Latin1_General_CS_AS = DESTINO.CODIGO COLLATE Latin1_General_CS_AS
WHERE
	DESTINO.CODIGO = '1000889'

-- Podemos observar que os vendedores possuem bairros associados a eles. 
-- Vamos aumentar em 30% o volume de compra dos clientes que possuem, em seus endereços, bairros onde os vendedores possuam escritórios.
-- Dica: vamos usar um UPDATE com FROM, usando o seguinte INNER JOIN:

SELECT
	*
FROM
	VENDEDORES

SELECT 
	*
FROM 
	CLIENTES

SELECT
	VENDEDORES.NOME AS [NOME VENDEDORES],
	VENDEDORES.BAIRRO AS [BAIRRO VENDEDORES],
	CLIENTES.NOME AS [NOME CLIENTES],
	CLIENTES.BAIRRO AS [BAIRRO CLIENTES],
	CLIENTES.[VOLUME COMPRA] AS [VOLUME COMPRA]
FROM
	VENDEDORES 
	INNER JOIN
	CLIENTES
	ON VENDEDORES.BAIRRO = CLIENTES.BAIRRO

UPDATE
	CLIENTES
SET
	CLIENTES.[VOLUME COMPRA] = CLIENTES.[VOLUME COMPRA] * 1.30
FROM 
	VENDEDORES 
	INNER JOIN
	CLIENTES
	ON VENDEDORES.BAIRRO = CLIENTES.BAIRRO

SELECT 
	*
FROM 
	CLIENTES

SELECT
	VENDEDORES.NOME AS [NOME VENDEDORES],
	VENDEDORES.BAIRRO AS [BAIRRO VENDEDORES],
	CLIENTES.NOME AS [NOME CLIENTES],
	CLIENTES.BAIRRO AS [BAIRRO CLIENTES],
	CLIENTES.[VOLUME COMPRA] AS [VOLUME COMPRA]
FROM
	VENDEDORES 
	INNER JOIN
	CLIENTES
	ON VENDEDORES.BAIRRO = CLIENTES.BAIRRO