CREATE TABLE [VENDEDORES]
(	[MATRICULA] [VARCHAR] (5),
	[NOME] [VARCHAR] (100),
	[PERCENTUAL COMISSAO] [FLOAT])

-- Incluindo um vendedor
INSERT INTO [VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00233', 'Jose Geraldo da Fonseca', 0.10) 


-- Incluindo dois vendedores de uma vez só
INSERT INTO [VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00235', 'Márcio Almeida Silva', 0.08) 

INSERT INTO [VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO])
VALUES
('00236', 'Cláudia Morais', 0.08)


-- Alterando registros dos vendedores
UPDATE [VENDEDORES] SET
[PERCENTUAL COMISSAO] = 0.11
WHERE [MATRICULA] = '00238'

UPDATE [VENDEDORES] SET
[NOME] = 'José Geral da Fonseca Junior'
WHERE [MATRICULA] = '00233'


DELETE FROM [VENDEDORES]
WHERE MATRICULA = '00233'



-- Alterando tabela de vendedores para incluir a chave primaria
ALTER TABLE [VENDEDORES]
ALTER COLUMN [MATRICULA]
VARCHAR(5) NOT NULL

ALTER TABLE VENDEDORES
ADD CONSTRAINT PK_MATRICULA
PRIMARY KEY CLUSTERED (MATRICULA)




-- Alterando a tabela de Vendedores para incluir a data de Admissao e Se esta de ferias
DROP TABLE [VENDEDORES]

CREATE TABLE [VENDEDORES]
(	[MATRICULA] [VARCHAR] (5) NOT NULL,
	[NOME] [VARCHAR] (100),
	[PERCENTUAL COMISSAO] [FLOAT],
	[DATA DE ADMISSAO] [DATE],
	[DE FERIAS] [BIT])

ALTER TABLE VENDEDORES
ADD CONSTRAINT PK_MATRICULA
PRIMARY KEY CLUSTERED (MATRICULA)

INSERT INTO [VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO], [DATA DE ADMISSAO], [DE FERIAS])
VALUES
('00235', 'Márcio Almeida Silva', 0.08, '2014-08-15', 0) 

INSERT INTO [VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO], [DATA DE ADMISSAO], [DE FERIAS])
VALUES
('00236', 'Cláudia Morais', 0.08, '2013-09-17', 1) 

INSERT INTO [VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO], [DATA DE ADMISSAO], [DE FERIAS])
VALUES
('00237', 'Roberta Martins', 0.11, '2017-03-18', 1)

INSERT INTO [VENDEDORES]
([MATRICULA], [NOME], [PERCENTUAL COMISSAO], [DATA DE ADMISSAO], [DE FERIAS])
VALUES
('00238', 'Pericles Alves', 0.11, '2016-08-21', 0) 


-- Selecionando o nome e matricula dos vendedores
SELECT NOME, MATRICULA FROM VENDEDORES

-- Selecionando o vendedor com o nome de Claudia Morais
SELECT * FROM VENDEDORES WHERE NOME = 'Cláudia Morais'

-- Selecionando Vendedores que possuem comisao maior que 10%
SELECT * FROM VENDEDORES WHERE [PERCENTUAL COMISSAO] > 0.1


-- Selecionando vendedores que foram admitidos na empresa depois de '16
SELECT * FROM VENDEDORES WHERE YEAR([DATA DE ADMISSAO]) >= 2016 
