-- Gerando relatórios

-- Montando o relatório passo a passo
SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT * FROM [NOTAS FISCAIS]

SELECT 
	*
FROM
	[NOTAS FISCAIS] NF
	INNER JOIN
	[ITENS NOTAS FISCAIS] INF
	ON NF.NUMERO = INF.NUMERO

SELECT 
	NF.CPF,
	CONVERT(VARCHAR, NF.DATA, 120) AS DATA_CONVERTIDA,
	INF.QUANTIDADE
FROM
	[NOTAS FISCAIS] NF
	INNER JOIN
	[ITENS NOTAS FISCAIS] INF
	ON NF.NUMERO = INF.NUMERO


-- Pegando o ano e mes
SELECT 
	NF.CPF,
	SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1, 7) AS ANO_MES,
	INF.QUANTIDADE
FROM
	[NOTAS FISCAIS] NF
	INNER JOIN
	[ITENS NOTAS FISCAIS] INF
	ON NF.NUMERO = INF.NUMERO

-- Agrupando por CPF e ano mes e somando a quantidade comprada
SELECT 
	NF.CPF,
	SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1, 7) AS ANO_MES,
	SUM(INF.QUANTIDADE) AS QUANTIDADE_MES
FROM
	[NOTAS FISCAIS] NF
	INNER JOIN
	[ITENS NOTAS FISCAIS] INF
	ON NF.NUMERO = INF.NUMERO
GROUP BY
	NF.CPF,
	SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1, 7)

-- Pegando as informações necessárias dos clientes, para logo juntar com a consulta de cima e mostrar o nome ao invés do CPF
SELECT TC.NOME, TC.[VOLUME DE COMPRA] FROM [TABELA DE CLIENTES] TC

-- Juntando as duas consultas anteriores. A consulta CQ fica como subquery e unimos com TC
-- para poder pegar o Nome do cliente e o Volume de compra
SELECT 
	TC.NOME,
	CQ.ANO_MES,
	CQ.QUANTIDADE_MES,
	TC.[VOLUME DE COMPRA]
FROM
	(SELECT 
		NF.CPF,
		SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1, 7) AS ANO_MES,
		SUM(INF.QUANTIDADE) AS QUANTIDADE_MES
	FROM
		[NOTAS FISCAIS] NF
		INNER JOIN
		[ITENS NOTAS FISCAIS] INF
		ON NF.NUMERO = INF.NUMERO
	GROUP BY
		NF.CPF,
		SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1, 7)) CQ
	INNER JOIN
	[TABELA DE CLIENTES] TC
	ON TC.CPF = CQ.CPF

-- Agora a consulta de cima vira uma subquery para assim podermos fazer a comparação entre o volume de compra e quantidade mes
SELECT 
	AUX1.NOME,
	AUX1.ANO_MES,
	AUX1.QUANTIDADE_MES,
CASE 
	WHEN AUX1.QUANTIDADE_MES <= AUX1.[VOLUME DE COMPRA] THEN 'VENDA VALIDA'
ELSE 'VENDA INVALIDA'
END AS [STATUS VENDA]
FROM
	(SELECT 
		TC.NOME,
		CQ.ANO_MES,
		CQ.QUANTIDADE_MES,
		TC.[VOLUME DE COMPRA]
	FROM
		(SELECT 
			NF.CPF,
			SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1, 7) AS ANO_MES,
			SUM(INF.QUANTIDADE) AS QUANTIDADE_MES
		FROM
			[NOTAS FISCAIS] NF
			INNER JOIN
			[ITENS NOTAS FISCAIS] INF
			ON NF.NUMERO = INF.NUMERO
		GROUP BY
			NF.CPF,
			SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1, 7)) CQ
		INNER JOIN
		[TABELA DE CLIENTES] TC
		ON TC.CPF = CQ.CPF) AUX1
ORDER BY
	AUX1.NOME,
	AUX1.ANO_MES

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- DESAFIO, agora vamos listas as vendas invalidas e calcular a diferença entre o limite de venda máximo
-- e o realizado em percentuais.
SELECT 
	AUX1.NOME,
	AUX1.ANO_MES,
	AUX1.[VOLUME DE COMPRA],
	AUX1.QUANTIDADE_MES,
CASE 
	WHEN AUX1.QUANTIDADE_MES <= AUX1.[VOLUME DE COMPRA] THEN 'VENDA VALIDA'
ELSE 'VENDA INVALIDA'
END AS [STATUS VENDA],
CONVERT(DECIMAL(15,2), (((AUX1.QUANTIDADE_MES / AUX1.[VOLUME DE COMPRA])-1) * 100)) as DIFERENCA
FROM
	(SELECT 
		TC.NOME,
		CQ.ANO_MES,
		CQ.QUANTIDADE_MES,
		TC.[VOLUME DE COMPRA]
	FROM
		(SELECT 
			NF.CPF,
			SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1, 7) AS ANO_MES,
			SUM(INF.QUANTIDADE) AS QUANTIDADE_MES
		FROM
			[NOTAS FISCAIS] NF
			INNER JOIN
			[ITENS NOTAS FISCAIS] INF
			ON NF.NUMERO = INF.NUMERO
		GROUP BY
			NF.CPF,
			SUBSTRING(CONVERT(VARCHAR, NF.DATA, 120), 1, 7)) CQ
		INNER JOIN
		[TABELA DE CLIENTES] TC
		ON TC.CPF = CQ.CPF) AUX1
WHERE
	AUX1.QUANTIDADE_MES > AUX1.[VOLUME DE COMPRA]
ORDER BY
	AUX1.NOME,
	AUX1.ANO_MES
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- GERANDO RELATORIO POR SABOR

-- Construindo passo a passo
-- Selecionando o que preciso de cada tabela
SELECT
	TP.SABOR
FROM 
	[TABELA DE PRODUTOS] TP

-- Selecionando o que preciso de cada tabela
SELECT
	NF.DATA
FROM 
	[NOTAS FISCAIS] NF

-- Selecionando o que preciso de cada tabela
SELECT
	INF.QUANTIDADE * INF.PREÇO AS FATURAMENTO
FROM 
	[ITENS NOTAS FISCAIS] INF

-- Juntando tudo o que preciso de cada tabela e juntando as tabelas por INNER JOIN
SELECT
	TP.SABOR,
	NF.DATA,
	(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM
	[TABELA DE PRODUTOS] TP
	INNER JOIN
	[ITENS NOTAS FISCAIS] INF
	ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
	INNER JOIN
	[NOTAS FISCAIS] NF
	ON
	NF.NUMERO = INF.NUMERO

-- Juntando por sabor e ano! E somando o faturamento de cada sabor
SELECT
	TP.SABOR,
	YEAR(NF.DATA) AS ANO,
	SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM
	[TABELA DE PRODUTOS] TP
	INNER JOIN
	[ITENS NOTAS FISCAIS] INF
	ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
	INNER JOIN
	[NOTAS FISCAIS] NF
	ON
	NF.NUMERO = INF.NUMERO
GROUP BY
	TP.SABOR,
	YEAR(NF.DATA)

-- Filtrando para ver so o ano de 2016
SELECT
	TP.SABOR,
	YEAR(NF.DATA) AS ANO,
	SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM
	[TABELA DE PRODUTOS] TP
	INNER JOIN
	[ITENS NOTAS FISCAIS] INF
	ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
	INNER JOIN
	[NOTAS FISCAIS] NF
	ON
	NF.NUMERO = INF.NUMERO
WHERE
	YEAR(NF.DATA) = 2016
GROUP BY
	TP.SABOR,
	YEAR(NF.DATA)

-- Uma consulta juntando por ano so
SELECT
	YEAR(NF.DATA) AS ANO,
	SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
FROM
	[TABELA DE PRODUTOS] TP
	INNER JOIN
	[ITENS NOTAS FISCAIS] INF
	ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
	INNER JOIN
	[NOTAS FISCAIS] NF
	ON
	NF.NUMERO = INF.NUMERO
WHERE
	YEAR(NF.DATA) = 2016
GROUP BY
	YEAR(NF.DATA)

-- Juntando as duas queries anteriores para obter o faturamento total e o faturamento por sabor
SELECT
	XSABOR.SABOR,
	XSABOR.ANO,
	CONVERT(DECIMAL(15,2), XSABOR.FATURAMENTO) AS FATURAMENTO,
	CONVERT(VARCHAR, CONVERT(DECIMAL(15,2),(XSABOR.FATURAMENTO / XANO.TOTAL) * 100)) + '%' AS PERCENTUAL
FROM
	(SELECT
		TP.SABOR,
		YEAR(NF.DATA) AS ANO,
		SUM(INF.QUANTIDADE * INF.PREÇO) AS FATURAMENTO
	FROM
		[TABELA DE PRODUTOS] TP
		INNER JOIN
		[ITENS NOTAS FISCAIS] INF
		ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
		INNER JOIN
		[NOTAS FISCAIS] NF
		ON
		NF.NUMERO = INF.NUMERO
	WHERE
		YEAR(NF.DATA) = 2016
	GROUP BY
		TP.SABOR,
		YEAR(NF.DATA)) XSABOR
	INNER JOIN
	(SELECT
		YEAR(NF.DATA) AS ANO,
		SUM(INF.QUANTIDADE * INF.PREÇO) AS TOTAL
	FROM
		[TABELA DE PRODUTOS] TP
		INNER JOIN
		[ITENS NOTAS FISCAIS] INF
		ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
		INNER JOIN
		[NOTAS FISCAIS] NF
		ON
		NF.NUMERO = INF.NUMERO
	WHERE
		YEAR(NF.DATA) = 2016
	GROUP BY
		YEAR(NF.DATA)) XANO
	ON XSABOR.ANO = XANO.ANO
ORDER BY
	XSABOR.FATURAMENTO DESC

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- GERANDO RELATORIO POR TAMANHO

-- VISUALIZANDO TODAS AS TABELAS
SELECT * FROM [TABELA DE PRODUTOS]

SELECT * FROM [NOTAS FISCAIS]

SELECT * FROM [ITENS NOTAS FISCAIS]

-- PEGANDO INFORMACOES NECESSARIAS

SELECT
	TP.[CODIGO DO PRODUTO],
	TP.TAMANHO
FROM
	[TABELA DE PRODUTOS] TP

SELECT 
	YEAR(NF.DATA),
	NF.NUMERO
FROM
	[NOTAS FISCAIS] NF

SELECT
	INF.NUMERO, 
	INF.[CODIGO DO PRODUTO],
	SUM((INF.QUANTIDADE * INF.PREÇO)) AS TOTAL
FROM
	[ITENS NOTAS FISCAIS] INF
GROUP BY
	INF.NUMERO,
	INF.[CODIGO DO PRODUTO]

-- Juntando a tabela de NF com INF e logo juntando com a tabela de produtos
SELECT
	TP.TAMANHO,
	YEAR(NF.DATA) AS ANO,
	SUM((INF.QUANTIDADE * INF.PREÇO)) AS TOTAL
FROM
	[NOTAS FISCAIS] NF
	INNER JOIN
	[ITENS NOTAS FISCAIS] INF
	ON NF.NUMERO = INF.NUMERO
	INNER JOIN
	[TABELA DE PRODUTOS] TP
	ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE 
	YEAR(NF.DATA) = 2016
GROUP BY
	TP.TAMANHO,
	YEAR(NF.DATA)

-- Juntando a tabela unicamente por ano
SELECT
	YEAR(NF.DATA) AS ANO,
	SUM((INF.QUANTIDADE * INF.PREÇO)) AS FATURAMENTO
FROM
	[NOTAS FISCAIS] NF
	INNER JOIN
	[ITENS NOTAS FISCAIS] INF
	ON NF.NUMERO = INF.NUMERO
	INNER JOIN
	[TABELA DE PRODUTOS] TP
	ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
WHERE 
	YEAR(NF.DATA) = 2016
GROUP BY
	YEAR(NF.DATA)

-- Juntando as duas consultas anteriores
SELECT
	XANO.ANO,
	XTAMANHO.TAMANHO,
	XTAMANHO.TOTAL,
	XANO.FATURAMENTO
FROM
	(
	SELECT
		TP.TAMANHO,
		YEAR(NF.DATA) AS ANO,
		SUM((INF.QUANTIDADE * INF.PREÇO)) AS TOTAL
	FROM
		[NOTAS FISCAIS] NF
		INNER JOIN
		[ITENS NOTAS FISCAIS] INF
		ON NF.NUMERO = INF.NUMERO
		INNER JOIN
		[TABELA DE PRODUTOS] TP
		ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
	WHERE 
		YEAR(NF.DATA) = 2016
	GROUP BY
		TP.TAMANHO,
		YEAR(NF.DATA)) XTAMANHO
	INNER JOIN
	(
	SELECT
		YEAR(NF.DATA) AS ANO,
		SUM((INF.QUANTIDADE * INF.PREÇO)) AS FATURAMENTO
	FROM
		[NOTAS FISCAIS] NF
		INNER JOIN
		[ITENS NOTAS FISCAIS] INF
		ON NF.NUMERO = INF.NUMERO
		INNER JOIN
		[TABELA DE PRODUTOS] TP
		ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
	WHERE 
		YEAR(NF.DATA) = 2016
	GROUP BY
		YEAR(NF.DATA)) XANO
	ON XTAMANHO.ANO = XANO.ANO

-- Como já temos o total e faturamento por cada um dos tamanhos, vamos fazer fazer o percentual
SELECT
	XTAMANHO.TAMANHO,
	XANO.ANO,
	XTAMANHO.FATURAMENTO,
	CONVERT(VARCHAR, CONVERT(DECIMAL(15,2),(XTAMANHO.FATURAMENTO  / XANO.TOTAL) * 100)) + '%' AS PERCENTUAL
FROM
	(
	SELECT
		TP.TAMANHO,
		YEAR(NF.DATA) AS ANO,
		SUM((INF.QUANTIDADE * INF.PREÇO)) AS FATURAMENTO
	FROM
		[NOTAS FISCAIS] NF
		INNER JOIN
		[ITENS NOTAS FISCAIS] INF
		ON NF.NUMERO = INF.NUMERO
		INNER JOIN
		[TABELA DE PRODUTOS] TP
		ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
	WHERE 
		YEAR(NF.DATA) = 2016
	GROUP BY
		TP.TAMANHO,
		YEAR(NF.DATA)) XTAMANHO
	INNER JOIN
	(
	SELECT
		YEAR(NF.DATA) AS ANO,
		SUM((INF.QUANTIDADE * INF.PREÇO)) AS TOTAL
	FROM
		[NOTAS FISCAIS] NF
		INNER JOIN
		[ITENS NOTAS FISCAIS] INF
		ON NF.NUMERO = INF.NUMERO
		INNER JOIN
		[TABELA DE PRODUTOS] TP
		ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
	WHERE 
		YEAR(NF.DATA) = 2016
	GROUP BY
		YEAR(NF.DATA)) XANO
	ON XTAMANHO.ANO = XANO.ANO
ORDER BY
	XTAMANHO.FATURAMENTO DESC