

SELECT * FROM MASTER.SYS.sql_logins

SELECT name, LOGINPROPERTY(name, 'PasswordLastSetTime') from MASTER.SYS.sql_logins

CREATE LOGIN pedro WITH PASSWORD = 'pedro'

SELECT SERVERPROPERTY('DESKTOP-N51LB16') AS SERVER_NAME
, NAME AS LOGIN_NAME FROM  MASTER.SYS.sql_logins
WHERE PWDCOMPARE(NAME, PASSWORD_HASH) <> 1

