CREATE TABLE VAGABENEFICIO
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	IdVaga INT NOT NULL FOREIGN KEY REFERENCES VAGA(ID),
	IdBeneficio INT NOT NULL FOREIGN KEY REFERENCES BENEFICIOS(ID)
);

CREATE TABLE ESCOLARIDADE
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(25) NOT NULL
)

EXEC sys.sp_rename N'dbo.INFO_CANDIDATO.ESCOLARIDADE' , N'FKEscolaridade', 'COLUMN';

ALTER TABLE INFO_CANDIDATO
ALTER COLUMN  FKEscolaridade INT

ALTER TABLE INFO_CANDIDATO
ADD CONSTRAINT FKEscolaridade
FOREIGN KEY (FKEscolaridade) REFERENCES ESCOLARIDADE(ID)
