-- Renomeando colunas

-- INFO CANDIDATO
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.INFOCANDIDATO.DATA DE NASCIMENTO' , N'DataDeNascimento', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.INFOCANDIDATO.ESCOLARIDADE' , N'Escolaridade', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.INFOCANDIDATO.IDVagaPrimaria' , N'IdVagaPrimaria', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.INFOCANDIDATO.IDVagaSecundaria' , N'IdVagaSecundaria', 'COLUMN';

-- ARQUIVO CANDIDATO
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.ARQUIVOCANDIDATO.FK_ARQUIVO_CANDIDATO' , N'FKArquivoCandidato', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.ARQUIVOCANDIDATO.NOME ARQUIVO' , N'NomeArquivo', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.ARQUIVOCANDIDATO.CAMINHO ARQUIVO' , N'CaminhoArquivo', 'COLUMN';


-- BENEFICIOS
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.BENEFICIOS.FK_ID_VAGA' , N'FKIdVaga', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.BENEFICIOS.NOME' , N'Nome', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.BENEFICIOS.ATIVO' , N'Ativo', 'COLUMN';

-- CONTATO CANDIDATO
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.CONTATOCANDIDATO.EMAIL' , N'Email', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.CONTATOCANDIDATO.TelefoneE' , N'Telefone', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.CONTATOCANDIDATO.LINKEDIN' , N'Linkedin', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.CONTATOCANDIDATO.GITHUB' , N'Github', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.CONTATOCANDIDATO.FK_CONTATO_CANDIDATO' , N'FKCPFCandidato', 'COLUMN';

-- ETAPA
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.ETAPA.NOME' , N'Nome', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.ETAPA.PARECER RH' , N'ParecerRH', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.ETAPA.DESCRiCAO PARECER RH' , N'DescricaoParecerRH', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.ETAPA.FK_ID_CANDIDATO' , N'FKIdCandidato', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.ETAPA.FK_ID_RH' , N'FKIdRH', 'COLUMN';

-- FUNCIONALIDADE
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.FUNCIONALIDADE.NOME' , N'Nome', 'COLUMN';

-- LOGIN
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.LOGIN.IDPerfil' , N'IdPerfil', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.LOGIN.HASH SENHA' , N'HashSenha', 'COLUMN';

-- PERFIL
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.PERFIL.NOME' , N'Nome', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.PERFIL.FKIDFuncionalidade' , N'FKIdFuncionalidade', 'COLUMN';

-- RH
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.RH.NOME' , N'Nome', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.RH.EMAIL' , N'Email', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.RH.CARGO' , N'Cargo', 'COLUMN';

-- VAGA
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.VAGA.TITULO' , N'Titulo', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.VAGA.DESCRICAO' , N'Descricao', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.VAGA.DATA ABERTURA' , N'DataAbertura', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.VAGA.TIPO' , N'Tipo', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.VAGA.SALARIO' , N'Salario', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.VAGA.BENEFICIOS' , N'Beneficios', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.VAGA.FKIDRH' , N'FKIdRH', 'COLUMN';
EXEC NTLABS_DEV.sys.sp_rename N'NTLABS_DEV.dbo.VAGA.QUANTIDADE' , N'Quantidade', 'COLUMN';





