CREATE TABLE FUNCIONALIDADE
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL
)

CREATE TABLE PERFIL
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	FK_ID_FUNDIONALIDADE INT NOT NULL FOREIGN KEY REFERENCES FUNCIONALIDADE(ID)
)

CREATE TABLE RH
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(100) NULL,
	CARGO VARCHAR(50) NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE
)

CREATE TABLE VAGA
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TITULO VARCHAR(150) NOT NULL,
	DESCRICAO VARCHAR(250) NULL,
	[DATA ABERTURA] DATE NULL,
	TIPO VARCHAR(7) NOT NULL,
	SALARIO INT NOT NULL,
	BENEFICIOS VARCHAR (20) NULL,
	FK_ID_RH INT NOT NULL FOREIGN KEY REFERENCES RH(ID),
	QUANTIDADE INT NOT NULL
)

CREATE TABLE BENEFICIOS
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	ATIVO BIT NOT NULL,
	FK_ID_VAGA INT NOT NULL FOREIGN KEY REFERENCES VAGA(ID)
)

CREATE TABLE ETAPA
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	[PARECER RH] VARCHAR(50) NULL,
	[DESCRICAO PARECER RH] VARCHAR(250) NULL,
	FK_ID_CANDIDATO VARCHAR(11) NOT NULL FOREIGN KEY REFERENCES INFO_CANDIDATO(CPF),
	FK_ID_RH INT NOT NULL FOREIGN KEY REFERENCES RH(ID)
)

CREATE TABLE LOGIN
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	[HASH SENHA] BINARY(64) NOT NULL,
	ID_PERFIL INT NOT NULL FOREIGN KEY REFERENCES PERFIL(ID)
)

ALTER TABLE INFO_CANDIDATO
DROP COLUMN [TIPO VAGA]

ALTER TABLE INFO_CANDIDATO
add ID_VAGA_PRIMARIA INT FOREIGN KEY REFERENCES  VAGA(ID)


ALTER TABLE INFO_CANDIDATO
add ID_VAGA_SECUNDARIA INT FOREIGN KEY REFERENCES  VAGA(ID)
