-- Agrupando os resultados do GROUP BY utilizando HAVING

-- HAVING é uma condição (Filtro) que se aplica ao rersultado de uma agregação

-- Por exemplo: 
SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) AS [LIMITE DE CREDITO] FROM [TABELA DE CLIENTES]
WHERE ESTADO = 'SP' GROUP BY BAIRRO, ESTADO

-- Aqui só mostramos aquelas linhas onde o valor da soma de credito é maior que 140k
SELECT BAIRRO, ESTADO, SUM([LIMITE DE CREDITO]) AS [LIMITE DE CREDITO] FROM [TABELA DE CLIENTES]
WHERE ESTADO = 'SP' GROUP BY BAIRRO, ESTADO HAVING SUM([LIMITE DE CREDITO]) >= 140000

SELECT ESTADO, SUM([LIMITE DE CREDITO]) AS [LIMITE DE CREDITO] FROM [TABELA DE CLIENTES]
GROUP BY ESTADO HAVING SUM([LIMITE DE CREDITO]) >= 850000

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) AS [SOMA DOS PRECOS], MAX([PREÇO DE LISTA]) AS [MAX DOS PRECOS], MIN([PREÇO DE LISTA]) AS [MIN DOS PRECOS]
FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]) AS [SOMA DOS PRECOS], MAX([PREÇO DE LISTA]) AS [MAX DOS PRECOS], MIN([PREÇO DE LISTA]) AS [MIN DOS PRECOS]
FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM HAVING SUM([PREÇO DE LISTA]) <= 80 AND MAX([PREÇO DE LISTA]) >= 6


-- Selecionando os clientes que fizeram mais de 2000 comprar em 2016
SELECT CPF, COUNT(*) FROM [NOTAS FISCAIS] WHERE YEAR(DATA) = 2016 GROUP BY CPF HAVING COUNT(*) > 2000