-- CAST AND CONVERT

-- Qual é a diferença entre CAST e CONVERT?
-- Ambos fazem a mesma coisa, porém o CAST é padrão SQL. Pode ser usado em outros bancos de dados.
-- O CONVERT é específico para SQL Server. Porém, pelo fato do CONVERT ser específico, ele possui funcionalidades mais complexas.

-- DATA e HORA (conversões)
-- CONVERT(<Tipo>, <Campo data>, <Estilo>)
-- Ex: CONVERT(VARCHAR, GETDATA(), 101) = 04/09/2018

SELECT CONVERT(VARCHAR, GETDATE(), 101)

SELECT CONVERT(VARCHAR, GETDATE(), 113)

SELECT CONVERT(VARCHAR, GETDATE(), 130)

SELECT CONVERT(decimal(10,5), 193.37)

SELECT 'O PREÇO DO PRODUTO ' + [NOME DO PRODUTO] + ' É ' + [PREÇO DE LISTA] FROM [TABELA DE PRODUTOS]

SELECT 'O PREÇO DO PRODUTO ' + [NOME DO PRODUTO] + ' É ' + CONVERT(VARCHAR, [PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS]

-- Queremos construir um SQL cujo resultado seja, para cada cliente: **"O cliente João da Silva faturou 120000 no ano de 2016".
-- Somente para o ano de 2016.

SELECT 
	'O CLIENTE ' + CLIENTES.NOME + ' FATUROU ' + CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), SUM(ITENS.QUANTIDADE * ITENS.PREÇO))) + ' NO ANO DE ' + CONVERT(VARCHAR, YEAR(NF.DATA))
FROM
	[NOTAS FISCAIS] NF
	INNER JOIN
	[ITENS NOTAS FISCAIS] ITENS
	ON NF.NUMERO = ITENS.NUMERO
	INNER JOIN
	[TABELA DE CLIENTES] CLIENTES
	ON NF.CPF = CLIENTES.CPF
WHERE
	YEAR(DATA) = 2016
GROUP BY 
	YEAR(DATA),
	CLIENTES.nome

	SELECT CONCAT('O cliente ', TC.NOME, ' faturou ', 
CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), SUM(INF.QUANTIDADE * INF.[PREÇO]))), ' no ano ',   CONVERT(VARCHAR, YEAR(NF.DATA))) AS SENTENCA FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE CLIENTES] TC ON NF.CPF = TC.CPF
WHERE YEAR(DATA) = 2016
GROUP BY TC.NOME, YEAR(DATA)