-- Declarando as variaveis
-- Elas estao aqui porque os nomes devem ser unico
DECLARE @MATRICULA VARCHAR(5), 
		@NOME VARCHAR(100),
		@PERCENTUAL FLOAT,
		@DATA DATE,
		@FERIAS BIT,
		@BAIRRO VARCHAR (100)

SET @MATRICULA = '00240'
SET	@NOME = 'Claudia Rodrigues'
SET @PERCENTUAL = 0.10
SET @DATA = '20120312'
SET @FERIAS = 1
SET @BAIRRO = 'Jardins'


INSERT INTO [TABELA DE VENDEDORES]
(MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], BAIRRO, [DE FERIAS])
VALUES
(@MATRICULA, @NOME, @PERCENTUAL, @DATA, @BAIRRO, @FERIAS)


SELECT
	*
FROM
	[TABELA DE VENDEDORES]