CREATE PROCEDURE [dbo].[InclusaoVendedor02] 
@MATRICULA AS VARCHAR(5), 
@NOME AS VARCHAR(100),
@PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, 
@FERIAS AS BIT, 
@BAIRRO AS VARCHAR(50),
@MENSAGEM VARCHAR(100) OUTPUT
AS
BEGIN
	BEGIN TRY
		INSERT INTO [TABELA DE VENDEDORES] 
			(MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
		VALUES 
			(@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
	END TRY
	BEGIN CATCH
		SET @MENSAGEM = 'Houve um erro número: ' + CONVERT(VARCHAR(30), @@ERROR)
	END CATCH
END

DECLARE @MENSAGEM VARCHAR(100)

SET @MENSAGEM = ''

EXEC InclusaoVendedor02'00238','Pericles Alves',0.11,'20160821',0,'Santo Amaro', @MENSAGEM OUTPUT

IF @MENSAGEM <> ''
	PRINT @MENSAGEM