CREATE TABLE ##TABELA02
	(ID VARCHAR(10) NULL,
	 NOME VARCHAR(200) NULL)

INSERT INTO ##TABELA02 (ID, NOME) VALUES (1, 'JOAO')

INSERT INTO ##TABELA02 (ID, NOME) VALUES (2, 'PEDRO')

SELECT * FROM ##TABELA02