-- Alterando essa SP
ALTER PROCEDURE [dbo].[TrataErroZeroTry2] 
@CPF VARCHAR(12),
@ANO INT,
@DENOMINADOR INT,
@MENSAGEM VARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		SELECT
			SUM(INF.QUANTIDADE * INF.[PREÇO]) AS FATURAMENTO,
			SUM(INF.QUANTIDADE * INF.[PREÇO]) / @DENOMINADOR AS COMISSAO
		FROM
			[ITENS NOTAS FISCAIS] INF
			INNER JOIN
			[NOTAS FISCAIS] NF
			ON INF.NUMERO = NF.NUMERO
		WHERE
			NF.CPF = @CPF
			AND
			YEAR(NF.DATA) = @ANO
	END TRY

	BEGIN CATCH
		SET @MENSAGEM = 'Houve um erro número: ' + CONVERT(VARCHAR(10), ERROR_MESSAGE()) + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Mensagem: ' + ERROR_MESSAGE() + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Grau de severidade do erro: ' + CONVERT(VARCHAR(10), ERROR_SEVERITY()) + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Estado do erro: ' + CONVERT(VARCHAR(10), ERROR_STATE()) + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Numero da linha: ' + CONVERT(VARCHAR(10), ERROR_LINE()) + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Procedure: ' + ERROR_PROCEDURE()
																  
	END CATCH													  
END																  

-- Declarando variaveis
DECLARE @DENOMINADOR INT,
		@CPF VARCHAR(12),
		@ANO INT,
		@MENSAGEM VARCHAR(MAX)

-- Setando valores
SET @CPF = '1471156710'
SET @ANO = 2016
SET @DENOMINADOR = 0
SET @MENSAGEM = ''


EXEC TrataErroZeroTry2 @CPF, @ANO, @DENOMINADOR, @MENSAGEM OUTPUT

IF @MENSAGEM <> ''
	PRINT @MENSAGEM


ALTER PROCEDURE [dbo].[InclusaoVendedor03] 
@MATRICULA AS VARCHAR(5), 
@NOME AS VARCHAR(100),
@PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, 
@FERIAS AS BIT, 
@BAIRRO AS VARCHAR(50),
@MENSAGEM VARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		INSERT INTO [TABELA DE VENDEDORES] 
			(MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
		VALUES 
			(@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
	END TRY
	BEGIN CATCH
		SET @MENSAGEM = 'Houve um erro número: ' + CONVERT(VARCHAR(10), ERROR_NUMBER()) + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Mensagem: ' + ERROR_MESSAGE() + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Grau de severidade do erro: ' + CONVERT(VARCHAR(10), ERROR_SEVERITY()) + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Estado do erro: ' + CONVERT(VARCHAR(10), ERROR_STATE()) + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Numero da linha: ' + CONVERT(VARCHAR(10), ERROR_LINE()) + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Procedure: ' + ERROR_PROCEDURE()
	END CATCH
END

DECLARE @MENSAGEM VARCHAR(MAX)

SET @MENSAGEM = ''

EXEC InclusaoVendedor03 '00238','Pericles Alves',0.11,'20160821',0,'Santo Amaro', @MENSAGEM OUTPUT

IF @MENSAGEM <> ''
	PRINT @MENSAGEM